export const MACHINE_FETCH_REQUEST = 'MACHINE_FETCH_REQUEST';
export const MACHINE_FETCH_SUCCESS = 'MACHINE_FETCH_SUCCESS';
export const MACHINE_FETCH_FAILURE = 'MACHINE_FETCH_FAILURE';

export const MACHINE_ADD_REQUEST = 'MACHINE_ADD_REQUEST';
export const MACHINE_ADD_SUCCESS = 'MACHINE_ADD_SUCCESS';
export const MACHINE_ADD_FAILURE = 'MACHINE_ADD_FAILURE';

export const MACHINE_REMOVE_REQUEST = 'MACHINE_REMOVE_REQUEST';
export const MACHINE_REMOVE_SUCCESS = 'MACHINE_REMOVE_SUCCESS';
export const MACHINE_REMOVE_FAILURE = 'MACHINE_REMOVE_FAILURE';
