// Message Statuses
export const ERROR = 'ERROR';
export const SUCCESS = 'SUCCESS';

// Global App Events
export const WEATHER_FETCH_REQUEST = 'WEATHER_FETCH_REQUEST';
export const WEATHER_FETCH_SUCCESS = 'WEATHER_FETCH_SUCCESS';
export const WEATHER_FETCH_FAILURE = 'WEATHER_FETCH_FAILURE';

export const SETTINGS_FETCH_REQUEST = 'SETTINGS_FETCH_REQUEST';
export const SETTINGS_FETCH_SUCCESS = 'SETTINGS_FETCH_SUCCESS';
export const SETTINGS_FETCH_FAILURE = 'SETTINGS_FETCH_FAILURE';
